#ifndef CHAINPARAMSSEEDS_H
#define CHAINPARAMSSEEDS_H
// List of fixed seed nodes for the bitcoin network
// AUTOGENERATED by contrib/devtools/generate-seeds.py

// Each line contains a 16-byte IPv6 address and a port.
// IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
static const unsigned int pnSeed[] =
{

    0x9fcb6d73,
    0x9fcb6d73

};


static const unsigned int pnTestnetSeed[] = {/*
    0x9fcb6d73,
    0xa2f3bab0,
    0x9fcb6a41,
    0x6883022b,
    0x68832296,
    0x951c7dd0,
    0x951c78d3,
    0x951c4d96,
    0x90ca77d7,
    0x951cc18d,
    0x2d4d0012,
    0xcf9af1db,
    0xa5e39c83,
    0x9f596873,
    0xcebd3977,
    0xcf9ac97d,
    0x9f5968e5,
    0xcf9af813,
    0x9f596404,
    0xcf9afebd,
    0x8a4462d7*/
};
#endif
